import { ref, computed, watch } from 'vue'

const currentLanguage = ref<'en' | 'de'>('en')

export const useLanguage = () => {
  // Initialize from localStorage
  if (typeof window !== 'undefined') {
    const savedLanguage = localStorage.getItem('imagio-language') as 'en' | 'de'
    if (savedLanguage && ['en', 'de'].includes(savedLanguage)) {
      currentLanguage.value = savedLanguage
    }
  }

  // Watch for language changes and persist to localStorage
  watch(currentLanguage, (newLang) => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('imagio-language', newLang)
      // Emit global event for other components
      window.dispatchEvent(new CustomEvent('languageChange', {
        detail: { language: newLang }
      }))
    }
  })

  const setLanguage = (lang: 'en' | 'de') => {
    currentLanguage.value = lang
  }

  const t = (key: string, translations: Record<string, Record<string, string>>) => {
    return translations[currentLanguage.value]?.[key] || translations['en']?.[key] || key
  }

  return {
    currentLanguage: computed(() => currentLanguage.value),
    setLanguage,
    t
  }
}

// Global translations
export const globalTranslations = {
  en: {
    home: 'Home',
    microphoneTest: 'Microphone Test',
    faq: 'FAQ',
    about: 'About the Game',
    admin: 'Admin',
    menu: 'Menu',
    close: 'Close',
    cancel: 'Cancel',
    login: 'Login',
    username: 'Username',
    password: 'Password',
    invalidCredentials: 'Invalid credentials',
    testMicrophone: 'Test your microphone here...',
    startTest: 'Start Test',
    transcription: 'Transcription:',
    // Page specific
    welcomeTitle: 'Welcome to IMAGIO',
    welcomeSubtitle: 'Enter your scenario code to begin',
    enterCode: 'Enter scenario code',
    startLearning: 'Start Learning',
    advancedLogin: 'Advanced Login',
    mainMenu: 'Main Menu',
    codeTooShort: 'Code must be at least 3 characters',
    // FAQ page
    faqTitle: 'Frequently Asked Questions',
    faqQuestion1: 'How do I start a scenario?',
    faqAnswer1: 'Enter your scenario code on the main page and click "Start Learning".',
    faqQuestion2: 'How do I test my microphone?',
    faqAnswer2: 'Click on "Microphone Test" in the menu to test your audio setup.',
    faqQuestion3: 'What browsers are supported?',
    faqAnswer3: 'IMAGIO works best with modern browsers like Chrome, Firefox, Safari, and Edge.',
    // About page
    aboutTitle: 'About IMAGIO',
    aboutDescription: 'IMAGIO is an innovative learning platform that uses interactive scenarios to enhance your learning experience.',
    aboutFeatures: 'Key Features:',
    aboutFeature1: 'Interactive voice-based scenarios',
    aboutFeature2: 'Real-time feedback and assessment',
    aboutFeature3: 'Multi-language support',
    aboutFeature4: 'Progress tracking and analytics',
    // Admin Dashboard
    adminDashboard: 'Admin Dashboard',
    scenarioManagement: 'Scenario Management',
    userManagement: 'User Management',
    scenarios: 'Scenarios',
    users: 'Users',
    addUser: 'Add User',
    remove: 'Remove',
    added: 'Added',
    status: 'Status',
    email: 'Email',
    createScenario: 'Create Scenario',
    code: 'Code',
    questions: 'Questions',
    questionsFor: 'Questions for',
    selectScenario: 'Select a Scenario',
    addQuestion: 'Add Question',
    enterQuestionText: 'Enter question text...',
    perfectAnswer: 'Perfect Answer',
    enterPerfectAnswer: 'Enter the perfect answer...',
    selectScenarioToManage: 'Select a scenario to manage questions',
    examSettings: 'Exam Settings',
    enterExamTitle: 'Enter exam title...',
    enterExamDescription: 'Enter exam description...',
    level: 'Level',
    sourceText: 'Source Text',
    enterSourceText: 'Enter source text...',
    back: 'Back',
    continue: 'Continue',
    examDetails: 'Exam Details',
    title: 'Title',
    updateExam: 'Update Exam',
    edit: 'Edit',
    delete: 'Delete',
    duration: 'Duration',
    type: 'Type',
    adminUsers: 'Admin Users',
    createUser: 'Create User',
    role: 'Role',
    created: 'Created',
    actions: 'Actions',
    createNewUser: 'Create New User',
    // Results Page
    resultsPortal: 'Results Portal',
    enterGameCode: 'Enter Game Code',
    enterGameCodeDescription: 'Enter the game code that was displayed during your IMAGIO session to view and manage your results.',
    gameCode: 'Game Code',
    gameCodePlaceholder: 'Enter your game code (e.g. ABC123)',
    loadResults: 'Load Results',
    gameCodeNotFound: 'Game code not found. Please check your code and try again.',
    backToCodeInput: 'Back to Code Input',
    audioRecordings: 'Audio Recordings',
    question: 'Question',
    recorded: 'Recorded',
    play: 'Play',
    pause: 'Pause',
    transcript: 'Transcript',
    save: 'Save',
    rating: 'Rating',
    poor: 'Poor',
    excellent: 'Excellent',
    exportResults: 'Export Results',
    exportPDF: 'Export PDF',
    exportCSV: 'Export CSV',
    // Exam Portal
    examPortal: 'Exam Portal',
    examManagement: 'Exam Management',
    generateQuestions: 'Generate Questions',
    questionGeneration: 'Question Generation',
    inputText: 'Input Text',
    textToAnalyze: 'Enter text to analyze and generate questions from',
    numberOfQuestions: 'Number of Questions',
    difficultyLevel: 'Difficulty Level',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    generateKeywords: 'Generate Keywords',
    keywords: 'Keywords',
    saveKeywords: 'Save Keywords',
    generatedKeywords: 'Generated Keywords',
    savedKeywords: 'Saved Keywords',
    generating: 'Generating...',
    examTitle: 'Exam Title',
    examDescription: 'Exam Description',
    reviewQuestions: 'Review Questions',
    selectQuestions: 'Select Questions',
    editExam: 'Edit Exam',
    finalizeExam: 'Finalize Exam',
    takeExam: 'Take Exam',
    examProgress: 'Exam Progress',
    submitAnswer: 'Submit Answer',
    nextQuestion: 'Next Question',
    previousQuestion: 'Previous Question',
    writtenMode: 'Written Mode',
    oralMode: 'Oral Mode',
    startRecording: 'Start Recording',
    stopRecording: 'Stop Recording',
    keywordsFound: 'Keywords Found',
    passed: 'Passed',
    failed: 'Failed',
    retakeExam: 'Retake Exam',
    levelLocked: 'Level Locked',
    unlockLevel: 'Unlock Level',
    examResults: 'Exam Results',
    completedExams: 'Completed Exams',
    availableExams: 'Available Exams'
  },
  de: {
    home: 'Start',
    microphoneTest: 'Mikrofon Test',
    faq: 'FAQ',
    about: 'Über das Spiel',
    admin: 'Admin',
    menu: 'Menü',
    close: 'Schließen',
    cancel: 'Abbrechen',
    login: 'Anmelden',
    username: 'Benutzername',
    password: 'Passwort',
    invalidCredentials: 'Falsche Anmeldedaten',
    testMicrophone: 'Teste dein Mikrofon hier...',
    startTest: 'Test starten',
    transcription: 'Transkription:',
    // Page specific
    welcomeTitle: 'Willkommen bei IMAGIO',
    welcomeSubtitle: 'Geben Sie Ihren Szenario-Code ein',
    enterCode: 'Szenario-Code eingeben',
    startLearning: 'Starten',
    advancedLogin: 'Erweiterte Anmeldung',
    mainMenu: 'Hauptmenü',
    codeTooShort: 'Code muss mindestens 3 Zeichen lang sein',
    // FAQ page
    faqTitle: 'Häufig gestellte Fragen',
    faqQuestion1: 'Wie starte ich ein Szenario?',
    faqAnswer1: 'Geben Sie Ihren Szenario-Code auf der Hauptseite ein und klicken Sie auf "Starten".',
    faqQuestion2: 'Wie teste ich mein Mikrofon?',
    faqAnswer2: 'Klicken Sie auf "Mikrofon Test" im Menü, um Ihr Audio-Setup zu testen.',
    faqQuestion3: 'Welche Browser werden unterstützt?',
    faqAnswer3: 'IMAGIO funktioniert am besten mit modernen Browsern wie Chrome, Firefox, Safari und Edge.',
    // About page
    aboutTitle: 'Über IMAGIO',
    aboutDescription: 'IMAGIO ist eine innovative Lernplattform, die interaktive Szenarien verwendet, um Ihr Lernerlebnis zu verbessern.',
    aboutFeatures: 'Hauptmerkmale:',
    aboutFeature1: 'Interaktive sprachbasierte Szenarien',
    aboutFeature2: 'Echtzeit-Feedback und Bewertung',
    aboutFeature3: 'Mehrsprachige Unterstützung',
    aboutFeature4: 'Fortschrittsverfolgung und Analysen',
    // Admin Dashboard
    adminDashboard: 'Admin Dashboard',
    scenarioManagement: 'Szenario-Verwaltung',
    userManagement: 'Benutzerverwaltung',
    scenarios: 'Szenarien',
    users: 'Benutzer',
    addUser: 'Benutzer hinzufügen',
    remove: 'Entfernen',
    added: 'Hinzugefügt',
    status: 'Status',
    email: 'E-Mail',
    createScenario: 'Szenario erstellen',
    code: 'Code',
    questions: 'Fragen',
    questionsFor: 'Fragen für',
    selectScenario: 'Szenario auswählen',
    addQuestion: 'Frage hinzufügen',
    enterQuestionText: 'Fragentext eingeben...',
    perfectAnswer: 'Perfekte Antwort',
    enterPerfectAnswer: 'Perfekte Antwort eingeben...',
    selectScenarioToManage: 'Wählen Sie ein Szenario aus, um Fragen zu verwalten',
    examSettings: 'Prüfungseinstellungen',
    enterExamTitle: 'Prüfungstitel eingeben...',
    enterExamDescription: 'Prüfungsbeschreibung eingeben...',
    level: 'Level',
    sourceText: 'Quelltext',
    enterSourceText: 'Quelltext eingeben...',
    back: 'Zurück',
    continue: 'Weiter',
    examDetails: 'Prüfungsdetails',
    title: 'Titel',
    updateExam: 'Prüfung aktualisieren',
    edit: 'Bearbeiten',
    delete: 'Löschen',
    duration: 'Dauer',
    type: 'Typ',
    adminUsers: 'Admin-Benutzer',
    createUser: 'Benutzer erstellen',
    role: 'Rolle',
    created: 'Erstellt',
    actions: 'Aktionen',
    createNewUser: 'Neuen Benutzer erstellen',
    // Results Page
    resultsPortal: 'Ergebnisportal',
    enterGameCode: 'Spielcode eingeben',
    enterGameCodeDescription: 'Geben Sie den Spielcode ein, der während Ihrer IMAGIO-Sitzung angezeigt wurde, um Ihre Ergebnisse anzuzeigen und zu verwalten.',
    gameCode: 'Spielcode',
    gameCodePlaceholder: 'Geben Sie Ihren Spielcode ein (z.B. ABC123)',
    loadResults: 'Ergebnisse laden',
    gameCodeNotFound: 'Spielcode nicht gefunden. Bitte überprüfen Sie Ihren Code und versuchen Sie es erneut.',
    backToCodeInput: 'Zurück zur Code-Eingabe',
    audioRecordings: 'Audioaufnahmen',
    question: 'Frage',
    recorded: 'Aufgenommen',
    play: 'Abspielen',
    pause: 'Pause',
    transcript: 'Transkript',
    save: 'Speichern',
    rating: 'Bewertung',
    poor: 'Schlecht',
    excellent: 'Ausgezeichnet',
    exportResults: 'Ergebnisse exportieren',
    exportPDF: 'PDF exportieren',
    exportCSV: 'CSV exportieren',
    // Exam Portal
    examPortal: 'Prüfungsportal',
    examManagement: 'Prüfungsverwaltung',
    generateQuestions: 'Fragen generieren',
    questionGeneration: 'Fragengenerierung',
    inputText: 'Text eingeben',
    textToAnalyze: 'Geben Sie den Text ein, der analysiert werden soll',
    numberOfQuestions: 'Anzahl Fragen',
    difficultyLevel: 'Schwierigkeitsgrad',
    easy: 'Leicht',
    medium: 'Mittel',
    hard: 'Schwer',
    generateKeywords: 'Keywords generieren',
    keywords: 'Schlüsselwörter',
    saveKeywords: 'Keywords speichern',
    generatedKeywords: 'Generierte Keywords',
    savedKeywords: 'Gespeicherte Keywords',
    generating: 'Generiere...',
    examTitle: 'Prüfungstitel',
    examDescription: 'Prüfungsbeschreibung',
    reviewQuestions: 'Fragen überprüfen',
    selectQuestions: 'Fragen auswählen',
    editExam: 'Prüfung bearbeiten',
    finalizeExam: 'Prüfung finalisieren',
    takeExam: 'Prüfung ablegen',
    examProgress: 'Prüfungsfortschritt',
    submitAnswer: 'Antwort abgeben',
    nextQuestion: 'Nächste Frage',
    previousQuestion: 'Vorherige Frage',
    writtenMode: 'Schriftlich',
    oralMode: 'Mündlich',
    startRecording: 'Aufnahme starten',
    stopRecording: 'Aufnahme stoppen',
    keywordsFound: 'Keywords gefunden',
    passed: 'Bestanden',
    failed: 'Nicht bestanden',
    retakeExam: 'Prüfung wiederholen',
    levelLocked: 'Level gesperrt',
    unlockLevel: 'Level freischalten',
    examResults: 'Prüfungsergebnisse',
    completedExams: 'Abgeschlossene Prüfungen',
    availableExams: 'Verfügbare Prüfungen'
  }
}