// Mock data for available requests on map - around Winnweiler
export const winnweilerCenter = { lat: 49.5467, lng: 7.7778 }

export const mapRequests = [
  // Winnweiler Center
  {
    id: 1,
    title: 'Einkaufen bei Familie Schmidt',
    type: 'shopping',
    area: 'Winnweiler',
    payment: 18,
    baseRate: 15,
    platformFee: 1.80,
    distance: '0.3km',
    position: { lat: 49.5467, lng: 7.7778 },
    circle: null,
    client: 'Familie Schmidt, 68/71 Jahre',
    clientRating: 4.9,
    clientReviews: 28,
    clientVerified: true,
    responseTime: '5 Min',
    urgency: 'normal',
    description: 'Wöchentlicher Großeinkauf bei Rewe. Spezialliste wird bereitgestellt. Hilfe beim Einpacken und Tragen gewünscht.',
    address: 'Hauptstraße 15, 67722 Winnweiler',
    estimatedDuration: '1.5 Stunden',
    specialRequirements: 'Kunde hat Gehprobleme, ruhiges Tempo erwünscht',
    privacyLevel: 'partial'
  },
  // Rockenhausen (5km)
  {
    id: 2,
    title: 'Gartenpflege bei Herrn Weber',
    type: 'gardening',
    area: 'Rockenhausen',
    payment: 25,
    baseRate: 20,
    platformFee: 2.50,
    distance: '4.8km',
    position: { lat: 49.5964, lng: 7.7213 },
    circle: null,
    client: 'Herr Weber, 74 Jahre',
    clientRating: 4.7,
    clientReviews: 19,
    clientVerified: true,
    responseTime: '15 Min',
    urgency: 'normal',
    description: 'Rasenmähen, Hecken schneiden und Unkraut entfernen. Garten ca. 200m².',
    address: 'Gartenstraße 8, 67808 Rockenhausen',
    estimatedDuration: '2.5 Stunden',
    specialRequirements: 'Eigenes Gartengerät vorhanden',
    privacyLevel: 'full'
  },
  // Imsweiler (3km)
  {
    id: 3,
    title: 'Technik-Hilfe für Seniorin',
    type: 'tech_help',
    area: 'Imsweiler',
    payment: 22,
    baseRate: 18,
    platformFee: 2.20,
    distance: '3.2km',
    position: { lat: 49.5689, lng: 7.8234 },
    circle: null,
    client: 'Anna Müller, 85 Jahre',
    clientRating: 5.0,
    clientReviews: 12,
    clientVerified: true,
    responseTime: '30 Min',
    urgency: 'high',
    description: 'Hilfe bei Videotelefonie mit Familie einrichten. WhatsApp und Skype installieren.',
    address: 'Dorfstraße 42, 67720 Imsweiler',
    estimatedDuration: '1 Stunde',
    specialRequirements: 'Geduld und einfache Erklärungen wichtig',
    privacyLevel: 'full'
  },
  // Bischweiler (7km)
  {
    id: 4,
    title: 'Haushaltshilfe gesucht',
    type: 'cleaning',
    area: 'Bischweiler',
    payment: 30,
    baseRate: 24,
    platformFee: 3.00,
    distance: '6.5km',
    position: { lat: 49.5987, lng: 7.6987 },
    circle: null,
    client: 'Ehepaar Bauer, 77/79 Jahre',
    clientRating: 4.8,
    clientReviews: 35,
    clientVerified: true,
    responseTime: '10 Min',
    urgency: 'normal',
    description: 'Wohnung reinigen (Böden wischen, Staub wischen), Bad putzen. 2-Zimmer-Wohnung.',
    address: 'Schulstraße 3, 67809 Bischweiler',
    estimatedDuration: '2 Stunden',
    specialRequirements: 'Reinigungsmittel vorhanden',
    privacyLevel: 'partial'
  },
  // Falkenstein (8km)
  {
    id: 5,
    title: 'Hund Gassi gehen',
    type: 'dog_walking',
    area: 'Falkenstein',
    payment: 12,
    baseRate: 10,
    platformFee: 1.20,
    distance: '7.8km',
    position: { lat: 49.5123, lng: 7.8123 },
    circle: null,
    client: 'Sabine Klein, 45 Jahre',
    clientRating: 4.6,
    clientReviews: 18,
    clientVerified: true,
    responseTime: '5 Min',
    urgency: 'normal',
    description: 'Golden Retriever (3 Jahre) benötigt täglichen Spaziergang. Ruhiges, freundliches Tier.',
    address: 'Am Wald 12, 67806 Falkenstein',
    estimatedDuration: '45 Minuten',
    specialRequirements: 'Tiererfahrung erforderlich',
    privacyLevel: 'full'
  },
  // Münsterappel (12km)
  {
    id: 6,
    title: 'Kochen für Single-Haushalt',
    type: 'cooking',
    area: 'Münsterappel',
    payment: 35,
    baseRate: 28,
    platformFee: 3.50,
    distance: '11.5km',
    position: { lat: 49.6234, lng: 7.6543 },
    circle: null,
    client: 'Karl Wagner, 82 Jahre',
    clientRating: 4.9,
    clientReviews: 22,
    clientVerified: true,
    responseTime: '20 Min',
    urgency: 'high',
    description: 'Vorkochen für 3 Tage. Einfache gesunde Kost. Diabetiker-Ernährung beachten.',
    address: 'Kirchweg 7, 67813 Münsterappel',
    estimatedDuration: '2.5 Stunden',
    specialRequirements: 'Diabetiker-kompetent wichtig',
    privacyLevel: 'partial'
  },
  // Ransweiler (4km)
  {
    id: 7,
    title: 'Fenster putzen',
    type: 'cleaning',
    area: 'Ransweiler',
    payment: 20,
    baseRate: 16,
    platformFee: 2.00,
    distance: '3.9km',
    position: { lat: 49.5789, lng: 7.8345 },
    circle: null,
    client: 'Familie Richter',
    clientRating: 4.5,
    clientReviews: 14,
    clientVerified: true,
    responseTime: '1 Stunde',
    urgency: 'normal',
    description: 'Fenster im Erdgeschoss putzen (6 Fenster). Leiter vorhanden.',
    address: 'Neue Straße 15, 67723 Ransweiler',
    estimatedDuration: '1.5 Stunden',
    specialRequirements: 'Keine Angst vor Höhen',
    privacyLevel: 'full'
  },
  // Schönborn (6km)
  {
    id: 8,
    title: 'Medikamentenabholung',
    type: 'shopping',
    area: 'Schönborn',
    payment: 15,
    baseRate: 12,
    platformFee: 1.50,
    distance: '5.7km',
    position: { lat: 49.5890, lng: 7.7567 },
    circle: null,
    client: 'Elisabeth Meier, 89 Jahre',
    clientRating: 5.0,
    clientReviews: 31,
    clientVerified: true,
    responseTime: '2 Min',
    urgency: 'high',
    description: 'Rezepte in Apotheke abholen und nach Hause bringen. Wichtig dringend!',
    address: 'Apothekenstraße 1, 67716 Schönborn',
    estimatedDuration: '30 Minuten',
    specialRequirements: 'Diskretion erforderlich',
    privacyLevel: 'full'
  }
]